### ISSUE TITLE
Nullpointer exception while trying to configure connector in Confluent Control Center

### ISSUE THREAD

**Issue by ghost** [kaliy/kafka-connect-rss#7] opened 2022-10-27 14:15 UTC
Hi,

i got the message 
Caused by: java.lang.NullPointerException
        at org.kaliy.kafka.connect.rss.config.UrlListValidator.ensureValid(UrlListValidator.java:18)
        at org.apache.kafka.common.config.ConfigDef.parseForValidate(ConfigDef.java:617)
        at org.apache.kafka.common.config.ConfigDef.parseForValidate(ConfigDef.java:551)
        at org.apache.kafka.common.config.ConfigDef.validateAll(ConfigDef.java:542)
        at org.apache.kafka.common.config.ConfigDef.validate(ConfigDef.java:525)
        at org.apache.kafka.connect.connector.Connector.validate(Connector.java:144)

while trying to configure the connector initial in the Confluent Control Center. I think it trys to check for the url before i even can type it in and runs into  NullpointerException (See https://github.com/kaliy/kafka-connect-rss/blob/kafka-connect-rss-0.1.0/src/main/java/org/kaliy/kafka/connect/rss/config/UrlListValidator.java) the call for 
        List<String> urlsAsList = Arrays.asList(urls.**split**(RSS_URL_SEPARATOR));

This should be handled different to make it able to configure via Control Center. 
![grafik](https://user-images.githubusercontent.com/85624727/198309724-da18d34d-2029-4ff6-9153-000d18d07c41.png)

Setup in Docker-Compose is the usual docker-compose from confluent-community version.

**Comment by kaliy** [comment] 2022-11-08 22:51
I managed to replicate the issue and will find the root cause and fix it. Thanks for the report!

**Comment by kaliy** [comment] 2022-11-24 20:22
The issue should be fixed now: https://github.com/kaliy/kafka-connect-rss/releases/download/kafka-connect-rss-0.1.1/kaliy-kafka-connect-rss-0.1.1.zip

Feel free to open the issue if something is still broken :)

**Closed as completed by kaliy** 2022-11-24 20:22 UTC

**Comment by ghost** [comment] 2022-11-25 08:41
Thanks for fixing. Can confirm the error no longer occurs.
